# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
    - mkdir outgoing
    - mkdir sent
    - echo 'test:$apr1$oOXGqDEk$G68MGAQ1eqsBEmL.ZrSbq0' > htpasswd.users

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
    - ./test.py
